### ISSUE TITLE
Home work1 

### ISSUE THREAD

**Issue by jagadeeshavvaru** [mnhaque/javaScriptTraining#1]
@mnhaque - please go through the comments and do necessary changes

1. printArray.js

please think about to seperate the same array elements with delimiter ;
Given solution works for comma(,) but write the code for delimiter ( ; ).

2. Opposite - No changes needed

3. Basic operations

Never use eval in javascript. If you use it as part of your code, there may be possiblity of cross site scripting. Please write without using eval

4. Rental car cost

-> You have chosen the varibals correctly.
-> Dont declare more than one variable in single statement.
-> Every if else statement should end with else statement. Instead defining the discount in the first line please move it to else block. You will end up in getting a sonar violation for not having else statement.

**Comment by mnhaque** [comment]
@jagadeeshavvaru made changes accordingly.
please verify

**Comment by mnhaque** [comment]
closing as addressed all feedbacks
